Delete problematic and outdated mac Maven profile
On an up to date OSX platform:

Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T05:39:06+10:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: US-ASCII
OS name: "mac os x", version: "10.13.1", arch: "x86_64", family: "mac"

Calling:
cd restygwt; mvn verify -Prun-its -Dmaven.test.skip -Dinvoker.test=restygwt-example

Fails with the following log:

[DEBUG] Module has an entrypoint
[DEBUG] Compilation not forced
[DEBUG] Execute command :
/bin/sh -c /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/bin/java -d32 -XstartOnFirstThread -Xmx512m -classpath /Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/war/WEB-INF/classes:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/src/main/java:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-core/2.8.4/jackson-core-2.8.4.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/google/gwt/gwt-user/2.5.1/gwt-user-2.5.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA-sources.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/org/json/json/20090211/json-20090211.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/org/fusesource/restygwt/restygwt/2.2.1/restygwt-2.2.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4-sources.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/github/nmorel/gwtjackson/gwt-jackson/0.14.2/gwt-jackson-0.14.2.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-annotations/2.8.4/jackson-annotations-2.8.4-sources.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/squareup/javapoet/1.0.0/javapoet-1.0.0.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/google/gwt/gwt-user/2.5.1/gwt-user-2.5.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/google/gwt/gwt-dev/2.5.1/gwt-dev-2.5.1.jar com.google.gwt.dev.Compiler -logLevel INFO -style DETAILED -war /Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/target/restygwt-example-2.2.1 -localWorkers 8 -treeLogger -XfragmentCount -1 -gen /Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/target org.fusesource.restygwt.examples.UI
[ERROR] Error: This Java instance does not support a 32-bit JVM.
[ERROR] Please install the desired version.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:31 min
[INFO] Finished at: 2017-11-05T14:58:48+11:00
[INFO] Final Memory: 26M/195M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.5.1:compile (default) on project restygwt-example: Command [[
[ERROR] /bin/sh -c /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/bin/java -d32 -XstartOnFirstThread -Xmx512m -classpath /Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/war/WEB-INF/classes:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/src/main/java:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-core/2.8.4/jackson-core-2.8.4.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/google/gwt/gwt-user/2.5.1/gwt-user-2.5.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA-sources.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/org/json/json/20090211/json-20090211.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/org/fusesource/restygwt/restygwt/2.2.1/restygwt-2.2.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4-sources.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/github/nmorel/gwtjackson/gwt-jackson/0.14.2/gwt-jackson-0.14.2.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-annotations/2.8.4/jackson-annotations-2.8.4-sources.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/squareup/javapoet/1.0.0/javapoet-1.0.0.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/google/gwt/gwt-user/2.5.1/gwt-user-2.5.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/google/gwt/gwt-dev/2.5.1/gwt-dev-2.5.1.jar com.google.gwt.dev.Compiler -logLevel INFO -style DETAILED -war /Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/target/restygwt-example-2.2.1 -localWorkers 8 -treeLogger -XfragmentCount -1 -gen /Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/target org.fusesource.restygwt.examples.UI
[ERROR] ]] failed with status 1
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.5.1:compile (default) on project restygwt-example: Command [[
/bin/sh -c /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/bin/java -d32 -XstartOnFirstThread -Xmx512m -classpath /Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/war/WEB-INF/classes:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/src/main/java:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-core/2.8.4/jackson-core-2.8.4.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/google/gwt/gwt-user/2.5.1/gwt-user-2.5.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA-sources.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/org/json/json/20090211/json-20090211.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/org/fusesource/restygwt/restygwt/2.2.1/restygwt-2.2.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4-sources.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/github/nmorel/gwtjackson/gwt-jackson/0.14.2/gwt-jackson-0.14.2.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-annotations/2.8.4/jackson-annotations-2.8.4-sources.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/squareup/javapoet/1.0.0/javapoet-1.0.0.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/google/gwt/gwt-user/2.5.1/gwt-user-2.5.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/google/gwt/gwt-dev/2.5.1/gwt-dev-2.5.1.jar com.google.gwt.dev.Compiler -logLevel INFO -style DETAILED -war /Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/target/restygwt-example-2.2.1 -localWorkers 8 -treeLogger -XfragmentCount -1 -gen /Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/target org.fusesource.restygwt.examples.UI
]] failed with status 1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.codehaus.mojo.gwt.shell.ForkedProcessExecutionException: Command [[
/bin/sh -c /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/bin/java -d32 -XstartOnFirstThread -Xmx512m -classpath /Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/war/WEB-INF/classes:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/src/main/java:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-core/2.8.4/jackson-core-2.8.4.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/google/gwt/gwt-user/2.5.1/gwt-user-2.5.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA-sources.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/org/json/json/20090211/json-20090211.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/org/fusesource/restygwt/restygwt/2.2.1/restygwt-2.2.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4-sources.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/github/nmorel/gwtjackson/gwt-jackson/0.14.2/gwt-jackson-0.14.2.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/fasterxml/jackson/core/jackson-annotations/2.8.4/jackson-annotations-2.8.4-sources.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/squareup/javapoet/1.0.0/javapoet-1.0.0.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/google/gwt/gwt-user/2.5.1/gwt-user-2.5.1.jar:/Users/freddyboucher/Programming/resty-gwt/restygwt/target/local-repo/com/google/gwt/gwt-dev/2.5.1/gwt-dev-2.5.1.jar com.google.gwt.dev.Compiler -logLevel INFO -style DETAILED -war /Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/target/restygwt-example-2.2.1 -localWorkers 8 -treeLogger -XfragmentCount -1 -gen /Users/freddyboucher/Programming/resty-gwt/restygwt/target/it/restygwt-example/target org.fusesource.restygwt.examples.UI
]] failed with status 1
	at org.codehaus.mojo.gwt.shell.AbstractGwtShellMojo$JavaCommand.execute(AbstractGwtShellMojo.java:485)
	at org.codehaus.mojo.gwt.shell.CompileMojo.compile(CompileMojo.java:365)
	at org.codehaus.mojo.gwt.shell.CompileMojo.doExecute(CompileMojo.java:280)
	at org.codehaus.mojo.gwt.shell.AbstractGwtShellMojo.execute(AbstractGwtShellMojo.java:172)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException